INSERT INTO NEWUSERS (FIRST_NAME, LAST_NAME, HEIGHTFT, HEIGHTIN, WEIGHT, AGE, EMAIL) VALUES ('Ryan', 'Cowles', '6', '0', '200', '25', 'rcowles3@gmail.com');

INSERT INTO NEWUSERS (FIRST_NAME, LAST_NAME, HEIGHTFT, HEIGHTIN, WEIGHT, AGE, EMAIL) VALUES ('Mark', 'Whalberg', '5', '7', '195', '45', 'markymark@gmail.com');